<%
vagrant_provider = ENV['VAGRANT_PROVIDER'] ? ENV['VAGRANT_PROVIDER'] : 'virtualbox'
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu1404
    driver:
      provider: <%= vagrant_provider %>
      box: box-cutter/ubuntu1404
      box_url: box-cutter/ubuntu1404
      customize:
        cpus: 2
        memory: 1024

  - name: centos70
    driver:
      provider: <%= vagrant_provider %>
      box: box-cutter/centos70
      box_url: box-cutter/centos70
      customize:
        cpus: 2
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[nodejs::default]
    attributes:

  - name: binary-latest
    run_list:
      - recipe[nodejs::binary]
    attributes:
      nodejs:
        version: 'latest'

  - name: binary-old-version
    run_list:
      - recipe[nodejs::binary]
    attributes:
      nodejs:
        version: '0.10.30'

  - name: package
    run_list:
      - recipe[nodejs::package]
    attributes:

  - name: source-latest
    run_list:
      - recipe[nodejs::source]
    attributes:
      nodejs:
        version: 'latest'

  - name: source-old-version
    run_list:
      - recipe[nodejs::source]
    attributes:
      nodejs:
        version: '0.10.30'
