<%
vagrant_provider = ENV['VAGRANT_PROVIDER'] ? ENV['VAGRANT_PROVIDER'] : 'virtualbox'
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu1404
    driver:
      provider: <%= vagrant_provider %>
      box: box-cutter/ubuntu1404
      box_url: box-cutter/ubuntu1404
      network:
      - ["private_network", {ip: "192.168.33.33"}]
      customize:
        cpus: 2
        memory: 1024

  - name: centos70
    driver:
      provider: <%= vagrant_provider %>
      box: box-cutter/centos70
      box_url: box-cutter/centos70
      network:
      - ["private_network", {ip: "192.168.33.34"}]
      customize:
        cpus: 2
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[nodejs::default]
    attributes:

  - name: binary
    run_list:
      - recipe[nodejs::binary]
    attributes:

  - name: package
    run_list:
      - recipe[nodejs::package]
    attributes:

  - name: source
    run_list:
      - recipe[nodejs::source]
    attributes:
